name: Merge Terraform Plugin Documentation Changes

on:
  push:
    branches:
    - main
    - stable-*

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate terraform docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: .
          output-method: inject
          git-push: "true"
          git-commit-message: 'Update Terraform Plugin Documentation'
          github-token: ${{ secrets.GITHUB_TOKEN }}
