name: Generate Terraform Plugin Documentation

on:
  pull_request:
    branches:
      - main
      - stable-*

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate terraform docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: .

      # - uses: actions/setup-go@v5
      #   with:
      #     go-version: 1.x

      # - name: Install dependencies
      #   run: go get .

      # - name: Install tfplugindocs
      #   run: go get github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs@latest

      # - name: Build
      #   run: go build -v ./...

      # - name: Generate documentation
      #   run: make generatedocs

